image: node:20.17.0

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .next/
  policy: pull-push

stages:
  - Install
  - Testing
  - Build
  - Deployment

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID
  VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

DEPENDENCIES_INSTALLATION:
  stage: Install
  cache: *global_cache
  script:
    - npm ci --legacy-peer-deps
    - npm install --save-dev typescript @types/react @types/node --legacy-peer-deps
    - du -sh node_modules/

TESTING:
  stage: Testing
  cache: *global_cache
  script:
    - npm run lint --if-present
    - npm run test --if-present

BUILD:
  stage: Build
  cache: *global_cache
  script:
    - npx prisma generate
    - npm run build

DEPLOYMENT_DEVELOPMENT:
  stage: Deployment
  only:
    - development
  cache: *global_cache
  before_script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - npx prisma generate
    - vercel pull --yes --environment=development --token $VERCEL_TOKEN
  script:
    - vercel build --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --token $VERCEL_TOKEN --alias $DEV_URL
  environment:
    name: development
    url: $DEV_URL


DEPLOYMENT_PREVIEW:
  stage: Deployment
  only:
    - staging
  cache: *global_cache
  script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - npx prisma generate
    - vercel pull --yes --environment=preview --token $VERCEL_TOKEN
    - vercel build --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --token $VERCEL_TOKEN --alias $STAGGING_URL
  environment:
    name: preview
    url: $STAGGING_URL

DEPLOYMENT_PRODUCTION:
  stage: Deployment
  only:
    - main
  script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - npx prisma generate
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
    - vercel build --prod --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN --alias $PRODUCTION_URL
  environment:
    name: production
    url: $PRODUCTION_URL

after_script:
  - echo "Cleaning up..."
  