image: node:20.17.0

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .next/
  policy: pull-push

stages:
  - Install
  - Testing
  - Build
  - Deployment

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID
  VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

DEPENDENCIES_INSTALLATION:
  stage: Install
  cache: *global_cache
  before_script:
    - rm -rf node_modules
  script:
    - npm ci --legacy-peer-deps
    - npm install --save-dev typescript @types/react @types/node @swc/core --legacy-peer-deps
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

TESTING:
  stage: Testing
  cache: *global_cache
  script:
    - npm run lint --if-present
    - npm run test --if-present
  artifacts:
    paths:
      - test-reports/
    expire_in: 1h

BUILD:
  stage: Build
  cache: *global_cache
  script:
    - npx prisma generate
    - npm run build
  artifacts:
    paths:
      - .next
    expire_in: 1h

DEPLOYMENT_PREVIEW:
  stage: Deployment
  only:
    - staging
  before_script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - vercel pull --yes --environment=preview --token $VERCEL_TOKEN
  script:
    - vercel build --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --token $VERCEL_TOKEN
  environment:
    name: preview
    url: $STAGGING_URL

DEPLOYMENT_PRODUCTION:
  stage: Deployment
  only:
    - main
  before_script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
  script:
    - vercel build --prod --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
  environment:
    name: production
    url: $PRODUCTION_URL

after_script:
  - echo "Cleaning up..."