image: node:20.17.0

# cache: &global_cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/
    - ~/.npm
  policy: pull-push

stages:
  - Install
  - Testing
  - Build
  - Deployment

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID
  VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

DEPENDENCIES_INSTALLATION:
  stage: Install
  # cache: *global_cache
  before_script:
    - rm -rf node_modules
    - ls -la node_modules/ || echo "No cache found"
  script:
    - npm ci --legacy-peer-deps
    - npm install --save-dev typescript @types/react @types/node --legacy-peer-deps
    - ls -la node_modules/
  # artifacts:
  #   paths:
  #     - node_modules/
  #   expire_in: 1h
  cache:
    key: ${CI_COMMIT_REF_SLUG}  # Use branch-specific cache
    paths:
      - node_modules/
      - ~/.npm
    policy: pull-push

TESTING:
  stage: Testing
  # cache: *global_cache
  before_script:
    - ls -la node_modules/ || echo "No cache found"
  script:
    - npm run lint --if-present
    - npm run test --if-present
  # artifacts:
  #   paths:
  #     - test-reports/
  #   expire_in: 1h
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - ~/.npm
    policy: pull

BUILD:
  stage: Build
  # cache: *global_cache
  before_script:
    - ls -la next/ || echo "No cache found"
  script:
    - npx prisma generate
    - npm run build
  # artifacts:
  #   paths:
  #     - .next
  #   expire_in: 1h
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/
    policy: pull-push

DEPLOYMENT_PREVIEW:
  stage: Deployment
  only:
    - staging
  cache: *global_cache  
  before_script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - vercel pull --yes --environment=preview --token $VERCEL_TOKEN
  script:
    - vercel build --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --token $VERCEL_TOKEN
  environment:
    name: preview
    url: $STAGGING_URL
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/
    policy: pull

DEPLOYMENT_PRODUCTION:
  stage: Deployment
  only:
    - main
  cache: *global_cache
  before_script:
    - npm config set legacy-peer-deps=true
    - npm install -g vercel
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
  script:
    - vercel build --prod --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
  environment:
    name: production
    url: $PRODUCTION_URL
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/
    policy: pull

after_script:
  - echo "Cleaning up..."